let editingId=null, chart=null;const $=id=>document.getElementById(id);
function money(v){return `₹${Number(v).toLocaleString('en-IN',{maximumFractionDigits:2})}`}
async function loadExpenses(){const p=new URLSearchParams({q:$('search').value,category:$('filterCategory').value});const r=await fetch(`/api/expenses?${p}`);const d=await r.json();$('total').textContent=money(d.total);$('count').textContent=d.count;$('average').textContent=money(d.average);$('budget').value=d.budget||'';const pct=d.budget?Math.min(d.total/d.budget*100,100):0;$('progressBar').style.width=`${pct}%`;$('budgetText').textContent=`Budget: ${money(d.budget)} | Spent: ${money(d.total)}`;const rows=$('expenseRows');rows.innerHTML='';$('empty').classList.toggle('hidden',d.expenses.length!==0);d.expenses.forEach(e=>{const tr=document.createElement('tr');tr.innerHTML=`<td>${e.date}</td><td>${safe(e.name)}</td><td>${money(e.amount)}</td><td><span class="badge">${safe(e.category)}</span></td><td><button class="action-btn edit" onclick="startEdit(${e.id})">Edit</button><button class="action-btn delete" onclick="removeExpense(${e.id})">Delete</button></td>`;rows.appendChild(tr)});updateChart(d.expenses)}
function safe(v){return v.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function updateChart(rows){const totals={};rows.forEach(e=>totals[e.category]=(totals[e.category]||0)+Number(e.amount);if(chart)chart.destroy();chart=new Chart($('expenseChart'),{type:'doughnut',data:{labels:Object.keys(totals),datasets:[{data:Object.values(totals)}]},options:{responsive:true,plugins:{legend:{position:'bottom'}}}})}
$('expenseForm').addEventListener('submit',async e=>{e.preventDefault();const body={date:$('date').value,name:$('name').value,amount:$('amount').value,category:$('category').value};const url=editingId?`/api/expenses/${editingId}`:'/api/expenses';const method=editingId?'PUT':'POST';const r=await fetch(url,{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok){$('message').textContent=d.error;return}resetForm();loadExpenses()});
async function startEdit(id){const d=await (await fetch('/api/expenses')).json();const e=d.expenses.find(x=>x.id===id);if(!e)return;editingId=id;$('formTitle').textContent='Edit Expense';$('saveBtn').textContent='Update Expense';$('cancelBtn').classList.remove('hidden');$('date').value=e.date;$('name').value=e.name;$('amount').value=e.amount;$('category').value=e.category;scrollTo({top:0,behavior:'smooth'})}
async function removeExpense(id){if(!confirm('Delete this expense?'))return;await fetch(`/api/expenses/${id}`,{method:'DELETE'});loadExpenses()}
function resetForm(){editingId=null;$('formTitle').textContent='Add Expense';$('saveBtn').textContent='Add Expense';$('cancelBtn').classList.add('hidden');$('expenseForm').reset();$('date').value=new Date().toISOString().slice(0,10);$('message').textContent=''}
$('cancelBtn').addEventListener('click',resetForm);$('search').addEventListener('input',loadExpenses);$('filterCategory').addEventListener('change',loadExpenses);$('budgetBtn').addEventListener('click',async()=>{const r=await fetch('/api/budget',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({budget:$('budget').value})});const d=await r.json();if(!r.ok){$('message').textContent=d.error;return}loadExpenses()});$('themeBtn').addEventListener('click',()=>{document.body.classList.toggle('dark');$('themeBtn').textContent=document.body.classList.contains('dark')?'☀️ Light Mode':'🌙 Dark Mode'});resetForm();loadExpenses();
